const ADIL = {
    docteur : {directoryTable:'طبيب', RequestTable:'Docteur', systemReady: true , FavoriteGenre:'Sante'},
    pharmacie : {directoryTable:'طاحب صيدلية', RequestTable:'Pharmacie', systemReady: false , FavoriteGenre:'PTVente'},
    clinique : {directoryTable:'صاحب مصحة', RequestTable:'Clinique', systemReady: false , FavoriteGenre:'Sante'},
    labo : {directoryTable:'صاحب مخبر طبي', RequestTable:'Labo', systemReady: false , FavoriteGenre:'Sante'},
    centreMD : {directoryTable:'صاحب مركز طبي', RequestTable:'CentreMD', systemReady: false , FavoriteGenre:'Sante'},
    admin_s_hospital : {directoryTable:'01a_hopitale', RequestTable:'Docteur2', systemReady: false , FavoriteGenre:'Admin'},
    admin_s_csb : {directoryTable:'01a_centre_sb', RequestTable:'Docteur2', systemReady: false , FavoriteGenre:'Admin'},

    garderie : {directoryTable:'صاحب روضة أطفال', RequestTable:'Garderie', systemReady: false , FavoriteGenre:'Education'},
    ecole : {directoryTable:'صاحب مدرسة خاصة', RequestTable:'Ecole', systemReady: false , FavoriteGenre:'Education'},
    lycee : {directoryTable:'صاحب معهد خاص', RequestTable:'Lycee', systemReady: false , FavoriteGenre:'Education'},
    universite : {directoryTable:'صاحب جامعة خاصة', RequestTable:'Universite', systemReady: false , FavoriteGenre:'Education'},
    impremerie : {directoryTable:'صاحب مطبعة', RequestTable:'Impremerie', systemReady: false , FavoriteGenre:'Education'},
    librairie : {directoryTable:'صاحب كتبية', RequestTable:'Librairie', systemReady: false , FavoriteGenre:'Education'},
    admin_e_centre : {directoryTable:'02a_centref', RequestTable:'Docteur2', systemReady: false , FavoriteGenre:'Admin'},
    admin_e_biblio : {directoryTable:'02a_bibliotheque', RequestTable:'Docteur2', systemReady: false , FavoriteGenre:'Admin'},
    admin_e_ecole : {directoryTable:'02a_ecole', RequestTable:'Docteur2', systemReady: false , FavoriteGenre:'Admin'},
    admin_e_lycee : {directoryTable:'02a_lycee', RequestTable:'Docteur2', systemReady: false , FavoriteGenre:'Admin'},
    admin_e_universite : {directoryTable:'02a_universite', RequestTable:'Docteur2', systemReady: false , FavoriteGenre:'Admin'},
    admin_e_ss : {directoryTable:'02_garderie', RequestTable:'Docteur2', systemReady: false , FavoriteGenre:'Admin'},

    transporteur : {directoryTable:'نقل بظائع', RequestTable:'Transporteur', systemReady: false , FavoriteGenre:'Transpo'},
    autoecole : {directoryTable:'صاحب مدرسة تعليم سياقة ', RequestTable:'AutoEcole', systemReady: false , FavoriteGenre:'Transpo'},

    cafe : {directoryTable:' صاحب مقهي ', RequestTable:'Cafe', systemReady: false , FavoriteGenre:'Life'},
    restaurant : {directoryTable:'صاحب مطعم ', RequestTable:'Restaurant', systemReady: true , FavoriteGenre:'Life'},
    magazin : {directoryTable:'صاحب مغازة ', RequestTable:'Magazin', systemReady: false , FavoriteGenre:'PTVente'},
    epicerie : {directoryTable:'صاحب مغازة ', RequestTable:'Magazin', systemReady: false , FavoriteGenre:'PTVente'},
    boulengerie : {directoryTable:'صاحب مخبزة', RequestTable:'Boulengerie', systemReady: false , FavoriteGenre:'PTVente'},
    boucherie : {directoryTable:'حزّار', RequestTable:'Boucherie', systemReady: false , FavoriteGenre:'PTVente'},
    fruiterie : {directoryTable:'خضّار', RequestTable:'Fruiterie', systemReady: false , FavoriteGenre:'PTVente'},
    patesserie : {directoryTable:'صاحب نقكة بيع المرطبات', RequestTable:'Patesserie', systemReady: false , FavoriteGenre:'PTVente'},

    electromenager : {directoryTable:'صاحب نقطة بيع الألكترونيات', RequestTable:'ElectroMenager', systemReady: false , FavoriteGenre:'PTVente'},
    meublerie : {directoryTable:'صاحب نقكة بيع الأثاث', RequestTable:'Meuble', systemReady: false , FavoriteGenre:'PTVente'},
    location : {directoryTable:'صاحب شركة كراء السيارات', RequestTable:'LocationVoiture', systemReady: false , FavoriteGenre:'Life'},
    parking : {directoryTable:'صاحب موقف سيارات', RequestTable:'Parking', systemReady: false , FavoriteGenre:'Life'},
    qiosque : {directoryTable:'صاحب محطة بيع الوقود', RequestTable:'Qiosque', systemReady: false , FavoriteGenre:'Life'},
    mecanicien : {directoryTable:'ميكانيكي', RequestTable:'Mecanicien', systemReady: false , FavoriteGenre:'Life'},

    samsar : {directoryTable:'سمسار  ', RequestTable:'Courtier', systemReady: false , FavoriteGenre:'Construct'},
    chantier_contrateur : {directoryTable:'مقاول', RequestTable:'Contracteur', systemReady: false , FavoriteGenre:'Construct'},
    chantier_architecture : {directoryTable:'مهندس معماري ', RequestTable:'Architecte', systemReady: false , FavoriteGenre:'Construct'},
    chantier_quincaillerie : {directoryTable:'صاحب محل معدات', RequestTable:'Quicaillerie', systemReady: false , FavoriteGenre:'Construct'},
    handmade_forgeron : {directoryTable:'حداد', RequestTable:'Forgeron', systemReady: false , FavoriteGenre:'Construct'},
    handmade_menuisier : {directoryTable:'نجار', RequestTable:'Menuisier', systemReady: false , FavoriteGenre:'Construct'},
    handmade_peinture : {directoryTable:'دهان', RequestTable:'Peintre', systemReady: false , FavoriteGenre:'Construct'},
    handmade_electricien : {directoryTable:'كهربائي', RequestTable:'Electricien', systemReady: false , FavoriteGenre:'Construct'},
    handmade_plombier : {directoryTable:'سباك', RequestTable:'Plombier', systemReady: false , FavoriteGenre:'Construct'},
    handmade_cristal : {directoryTable:'تركيب البلور', RequestTable:'Cristallerie', systemReady: false , FavoriteGenre:'Construct'},
    handmade_marbre : {directoryTable:'بيع الرخام ', RequestTable:'Marberie', systemReady: false , FavoriteGenre:'Construct'},

    coiffure : {directoryTable:'صاحب قاعة حلاقة', RequestTable:'Coiffure', systemReady: false , FavoriteGenre:'Life'},
    boutique : {directoryTable:'صاحب نقطة بيع الملابس', RequestTable:'Boutique', systemReady: false , FavoriteGenre:'PTVente'},
    wedding_salon_marriage : {directoryTable:'صاحب قاعة أفراح', RequestTable:'SllonMariage', systemReady: false , FavoriteGenre:'Life'},
    wedding_orchestre : {directoryTable:'صاحب فرقة موسيقية', RequestTable:'Orchestre', systemReady: false , FavoriteGenre:'Life'},
    wedding_chef : {directoryTable:'طباخ', RequestTable:'ChefCuisinier', systemReady: false , FavoriteGenre:'Life'},
    wedding_photographe : {directoryTable:'مصور', RequestTable:'Photographe', systemReady: false , FavoriteGenre:'Life'},
    wedding_fourniture_marriage : {directoryTable:'صاحب نقطة بيع لوازم الأفراح', RequestTable:'FournitureMariage', systemReady: false , FavoriteGenre:'Life'},
    wedding_bijoux : {directoryTable:'صاحب نقطة بيع المجوهرات', RequestTable:'Bijouterie', systemReady: false , FavoriteGenre:'Life'},

    gym : {directoryTable:'صاحب قاعة رياضة', RequestTable:'Gym', systemReady: false , FavoriteGenre:'Sport'},
    pyscine : {directoryTable:'صاحب مسبح ', RequestTable:'Pyscine', systemReady: false , FavoriteGenre:'Sport'},
    stade : {directoryTable:'صاحب ملعب رياضي', RequestTable:'Stade', systemReady: false , FavoriteGenre:'Sport'},
    art_cinema : {directoryTable:'صاحب قاعة سنما', RequestTable:'Cinma', systemReady: false , FavoriteGenre:'Sport'},
    art_theatre : {directoryTable:'صاحب مسرح', RequestTable:'Theatre', systemReady: false , FavoriteGenre:'Sport'},
    art_musee : {directoryTable:'صاحب متحف', RequestTable:'Musee', systemReady: false , FavoriteGenre:'Sport'},
    admin_c_mj : {directoryTable:'06a_jeune_ma', RequestTable:'Docteur2', systemReady: false , FavoriteGenre:'Admin'},
    admin_c_mc : {directoryTable:'06a_culture_ma', RequestTable:'Docteur2', systemReady: false , FavoriteGenre:'Admin'},
    admin_c_me : {directoryTable:'06a_enfant_ma', RequestTable:'Docteur2', systemReady: false , FavoriteGenre:'Admin'},

    avocat : {directoryTable:'محامي', RequestTable:'Avocat', systemReady: false , FavoriteGenre:'Other'},

    storage : {directoryTable:'صاحب نقطة بيه بالجملة ', RequestTable:'PTVGros', systemReady: false , FavoriteGenre:'PTVente'},
    comptable : {directoryTable:'محاسب', RequestTable:'Comptable', systemReady: false , FavoriteGenre:'Other'},
    socite : {directoryTable:'صاحب شركة قابضة', RequestTable:'Socite', systemReady: false , FavoriteGenre:'Other'},
    admin_f_poste : {directoryTable:'08a_poste', RequestTable:'Docteur2', systemReady: false , FavoriteGenre:'Admin'},
    admin_f_rf : {directoryTable:'08a_recipe', RequestTable:'Docteur2', systemReady: false , FavoriteGenre:'Admin'},

    hotels : {directoryTable:'صاحب نزل ', RequestTable:'Hotels', systemReady: false , FavoriteGenre:'Life'},
    vg_agence : {directoryTable:'صاحب وكالة أسفار', RequestTable:'AgenceVoiyage', systemReady: false , FavoriteGenre:'Life'},

    admin_a_mu : {directoryTable:'00_municipalite', RequestTable:'Docteur2', systemReady: false , FavoriteGenre:'Admin'},
    admin_a_police : {directoryTable:'00_police', RequestTable:'Docteur2', systemReady: false , FavoriteGenre:'Admin'},
    admin_a_ar : {directoryTable:'00_admin_regionale', RequestTable:'Docteur2', systemReady: false , FavoriteGenre:'Admin'},
    admin_a_court : {directoryTable:'00_cour', RequestTable:'Docteur2', systemReady: false , FavoriteGenre:'Admin'},
    admin_a_mosq : {directoryTable:'00_mosquee', RequestTable:'Docteur2', systemReady: false , FavoriteGenre:'Admin'},
    ambassade : {directoryTable:'00_ambassade', RequestTable:'Docteur2', systemReady: false , FavoriteGenre:'Admin'},
}

module.exports = ADIL