const SubCat = {
    sante : {
        tableName: '000_abyedh_medicamment' ,
        searchGenre : 'Forme',
        searchSousGenre : 'Forme',
        subCategories : [
            {id:1, genre:'أدوية', name:'Solution injectable' , tag:'Solution injectable', icon:'' , image:'Products/medicamment.jpg'},
            {id:2, genre:'أدوية', name:'Solution injectable pour perfusion' , tag:'Solution injectable pour perfusion', icon:'' , image:'Products/medicamment.jpg'},
            {id:3, genre:'أدوية', name:'Poudre pour suspension orale' , tag:'Poudre pour suspension orale', icon:'' , image:'Products/medicamment.jpg'},
            {id:4, genre:'أدوية', name:'Solution à diluer pour perfusion' , tag:'Solution à diluer pour perfusion', icon:'' , image:'Products/medicamment.jpg'},
            {id:5, genre:'أدوية', name:'Comprimé' , tag:'Comprimé', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'Comprimé pelliculé sécable' , tag:'Comprimé pelliculé sécable', icon:'' , image:'Products/medicamment.jpg'},
            {id:7, genre:'أدوية', name:'Comprimé pelliculé' , tag:'Comprimé pelliculé', icon:'' , image:'Products/medicamment.jpg'},
            {id:8, genre:'أدوية', name:'Pdre p.prep.injectable' , tag:'Pdre p.prep.injectable', icon:'' , image:'Products/medicamment.jpg'},
            {id:9, genre:'أدوية', name:'Creme dermique' , tag:'Creme dermique', icon:'' , image:'Products/medicamment.jpg'},
            {id:10, genre:'أدوية', name:'Suspension buvable' , tag:'Suspension buvable', icon:'' , image:'Products/medicamment.jpg'},
            {id:11, genre:'أدوية', name:'Comprimé sécable' , tag:'Comprimé sécable', icon:'' , image:'Products/medicamment.jpg'},
            {id:12, genre:'أدوية', name:'Gélule' , tag:'Gélule', icon:'' , image:'Products/medicamment.jpg'},
            {id:13, genre:'أدوية', name:'Gel dermique' , tag:'Gel dermique', icon:'' , image:'Products/medicamment.jpg'},
            {id:14, genre:'أدوية', name:'Comprimé orodispersible' , tag:'Comprimé orodispersible', icon:'' , image:'Products/medicamment.jpg'},
            {id:15, genre:'أدوية', name:'Solution buvable' , tag:'Solution buvable', icon:'' , image:'Products/medicamment.jpg'},
            {id:16, genre:'أدوية', name:'Gélule gastrorésistante' , tag:'Gélule gastrorésistante', icon:'' , image:'Products/medicamment.jpg'},
            {id:17, genre:'أدوية', name:'Suspension buvable ou nasale' , tag:'Suspension buvable ou nasale', icon:'' , image:'Products/medicamment.jpg'},
            {id:18, genre:'أدوية', name:'Solution pour pulvérisation buccale' , tag:'Solution pour pulvérisation buccale', icon:'' , image:'Products/medicamment.jpg'},
            {id:19, genre:'أدوية', name:'Granulés pour solution buvable' , tag:'Granulés pour solution buvable', icon:'' , image:'Products/medicamment.jpg'},
            {id:20, genre:'أدوية', name:'Suspension injectable' , tag:'Suspension injectable', icon:'' , image:'Products/medicamment.jpg'},
            {id:21, genre:'أدوية', name:'Comprime enrobe secable' , tag:'Comprime enrobe secable', icon:'' , image:'Products/medicamment.jpg'},
            {id:22, genre:'أدوية', name:'Comprimé à libération prolongée' , tag:'Comprimé à libération prolongée', icon:'' , image:'Products/medicamment.jpg'},
            {id:23, genre:'أدوية', name:'Gouttes buvables' , tag:'Gouttes buvables', icon:'' , image:'Products/medicamment.jpg'},
            {id:24, genre:'أدوية', name:'Gélule à libération prolongée' , tag:'Gélule à libération prolongée', icon:'' , image:'Products/medicamment.jpg'},
            {id:25, genre:'أدوية', name:'Aérosol' , tag:'Aérosol', icon:'' , image:'Products/medicamment.jpg'},
        ]
    },
    transport : {
        tableName: '000_abyedh_medicamment' ,
        searchGenre : 'Forme',
        searchSousGenre : 'Forme',
        subCategories : [
            {id:1, genre:'أدوية', name:'Alfa Romeo' , tag:'Alfa Romeo', icon:'' , image:'Products/transport.png'},
            {id:2, genre:'أدوية', name:'Audi' , tag:'Audi', icon:'' , image:'Products/transport.png'},
            {id:3, genre:'أدوية', name:'Bestune' , tag:'Bestune', icon:'' , image:'Products/transport.png'},
            {id:4, genre:'أدوية', name:'BMW' , tag:'BMW', icon:'' , image:'Products/transport.png'},
            {id:5, genre:'أدوية', name:'BYD' , tag:'BYD', icon:'' , image:'Products/transport.png'},
            {id:6, genre:'أدوية', name:'Changan' , tag:'Changan', icon:'' , image:'Products/transport.png'},
            {id:7, genre:'أدوية', name:'Chery' , tag:'Chery', icon:'' , image:'Products/transport.png'},
            {id:8, genre:'أدوية', name:'Chevrolet' , tag:'Chevrolet', icon:'' , image:'Products/transport.png'},
            {id:9, genre:'أدوية', name:'Cupra' , tag:'Cupra', icon:'' , image:'Products/transport.png'},
            {id:10, genre:'أدوية', name:'Dacia' , tag:'Dacia', icon:'' , image:'Products/transport.png'},
            {id:11, genre:'أدوية', name:'DFSK' , tag:'DFSK', icon:'' , image:'Products/transport.png'},
            {id:12, genre:'أدوية', name:'Dongfeng' , tag:'Dongfeng', icon:'' , image:'Products/transport.png'},
            {id:13, genre:'أدوية', name:'Faw' , tag:'Faw', icon:'' , image:'Products/transport.png'},
            {id:14, genre:'أدوية', name:'Fiat' , tag:'Fiat', icon:'' , image:'Products/transport.png'},
            {id:15, genre:'أدوية', name:'Foday' , tag:'Foday', icon:'' , image:'Products/transport.png'},
            {id:16, genre:'أدوية', name:'Ford' , tag:'Ford', icon:'' , image:'Products/transport.png'},
            {id:17, genre:'أدوية', name:'GAC' , tag:'GAC', icon:'' , image:'Products/transport.png'},
            {id:18, genre:'أدوية', name:'Geely' , tag:'Geely', icon:'' , image:'Products/transport.png'},
            {id:19, genre:'أدوية', name:'Great' , tag:'Great', icon:'' , image:'Products/transport.png'},
            {id:20, genre:'أدوية', name:'Haval' , tag:'Haval', icon:'' , image:'Products/transport.png'},
            {id:21, genre:'أدوية', name:'Honda' , tag:'Honda', icon:'' , image:'Products/transport.png'},
            {id:22, genre:'أدوية', name:'Huanghai' , tag:'Huanghai', icon:'' , image:'Products/transport.png'},
            {id:23, genre:'أدوية', name:'Hyundai' , tag:'Hyundai', icon:'' , image:'Products/transport.png'},
            {id:24, genre:'أدوية', name:'Jaguar' , tag:'Jaguar', icon:'' , image:'Products/transport.png'},
            {id:25, genre:'أدوية', name:'Jeep' , tag:'Jeep', icon:'' , image:'Products/transport.png'},
            {id:26, genre:'أدوية', name:'KIA' , tag:'KIA', icon:'' , image:'Products/transport.png'},
            {id:27, genre:'أدوية', name:'Land Rover' , tag:'Land Rover', icon:'' , image:'Products/transport.png'},
            {id:28, genre:'أدوية', name:'Mahindra' , tag:'Mahindra', icon:'' , image:'Products/transport.png'},
            {id:29, genre:'أدوية', name:'Mercedes-Benz' , tag:'Mercedes-Benz', icon:'' , image:'Products/transport.png'},
            {id:30, genre:'أدوية', name:'MG' , tag:'MG', icon:'' , image:'Products/transport.png'},
            {id:31, genre:'أدوية', name:'Mini' , tag:'Mini', icon:'' , image:'Products/transport.png'},
            {id:32, genre:'أدوية', name:'Mitsubishi' , tag:'Mitsubishi', icon:'' , image:'Products/transport.png'},
            {id:33, genre:'أدوية', name:'Nissan' , tag:'Nissan', icon:'' , image:'Products/transport.png'},
            {id:34, genre:'أدوية', name:'Opel' , tag:'Opel', icon:'' , image:'Products/transport.png'},
            {id:35, genre:'أدوية', name:'Peugeot' , tag:'Peugeot', icon:'' , image:'Products/transport.png'},
            {id:36, genre:'أدوية', name:'Porsche' , tag:'Porsche', icon:'' , image:'Products/transport.png'},
            {id:37, genre:'أدوية', name:'Renault' , tag:'Renault', icon:'' , image:'Products/transport.png'},
            {id:38, genre:'أدوية', name:'Seat' , tag:'Seat', icon:'' , image:'Products/transport.png'},
            {id:39, genre:'أدوية', name:'Skoda' , tag:'Skoda', icon:'' , image:'Products/transport.png'},
            {id:40, genre:'أدوية', name:'Soueast' , tag:'Soueast', icon:'' , image:'Products/transport.png'},
            {id:41, genre:'أدوية', name:'Ssangyong' , tag:'Ssangyong', icon:'' , image:'Products/transport.png'},
            {id:42, genre:'أدوية', name:'Suzuki' , tag:'Suzuki', icon:'' , image:'Products/transport.png'},
            {id:43, genre:'أدوية', name:'Tata' , tag:'Tata', icon:'' , image:'Products/transport.png'},
            {id:44, genre:'أدوية', name:'Toyota' , tag:'Toyota', icon:'' , image:'Products/transport.png'},
            {id:45, genre:'أدوية', name:'Volkswagen' , tag:'Volkswagen', icon:'' , image:'Products/transport.png'},
            {id:46, genre:'أدوية', name:'Volvo' , tag:'Volvo', icon:'' , image:'Products/transport.png'},
            {id:47, genre:'أدوية', name:'Wallyscar' , tag:'Wallyscar', icon:'' , image:'Products/transport.png'},
        ]
    },
    education : {
        tableName: '000_abyedh_medicamment' ,
        searchGenre : 'Forme',
        searchSousGenre : 'Forme',
        subCategories : [
            {id:1, genre:'أدوية', name:'Livres' , tag:'Livres', icon:'' , image:'Products/education.png'},
            {id:2, genre:'أدوية', name:'Chaiers & Bloc & Registres' , tag:'Chaiers & Bloc & Registres', icon:'' , image:'Products/education.png'},
            {id:3, genre:'أدوية', name:'Agendas & Calendriers' , tag:'Agendas & Calendriers', icon:'' , image:'Products/education.png'},
            {id:4, genre:'أدوية', name:'Courrier & Correspondances' , tag:'Courrier & Correspondances', icon:'' , image:'Products/education.png'},
            {id:5, genre:'أدوية', name:'Archivage & Classement' , tag:'Archivage & Classement', icon:'' , image:'Products/education.png'},
            {id:6, genre:'أدوية', name:'Chemises & Présentation des Documents' , tag:'Chemises & Présentation des Documents', icon:'' , image:'Products/education.png'},
            {id:7, genre:'أدوية', name:'Trieurs & Protection des Documents' , tag:'Trieurs & Protection des Documents', icon:'' , image:'Products/education.png'},
            {id:8, genre:'أدوية', name:'Modules & Accessoires de Organisation' , tag:'Modules & Accessoires de Organisation', icon:'' , image:'Products/education.png'},
            {id:9, genre:'أدوية', name:'Ecriture & Correction' , tag:'Ecriture & Correction', icon:'' , image:'Products/education.png'},
            {id:10, genre:'أدوية', name:'Agrafage' , tag:'Agrafage', icon:'' , image:'Products/education.png'},
            {id:11, genre:'أدوية', name:'Perforation' , tag:'Perforation', icon:'' , image:'Products/education.png'},
            {id:12, genre:'أدوية', name:'Classeurs & Intercalaires' , tag:'Classeurs & Intercalaires', icon:'' , image:'Products/education.png'},
            {id:13, genre:'أدوية', name:'Colles & Adhésifs' , tag:'Colles & Adhésifs', icon:'' , image:'Products/education.png'},
            {id:14, genre:'أدوية', name:'Petite Fournitures de Bureau' , tag:'Petite Fournitures de Bureau', icon:'' , image:'Products/education.png'},
            {id:15, genre:'أدوية', name:'Calculatrices & Piles' , tag:'Calculatrices & Piles', icon:'' , image:'Products/education.png'},
            {id:16, genre:'أدوية', name:'Destructeurs de Papier & Instruments de Coupe' , tag:'Destructeurs de Papier & Instruments de Coupe', icon:'' , image:'Products/education.png'},
            {id:17, genre:'أدوية', name:'Imprimantes & Consommables' , tag:'Imprimantes & Consommables', icon:'' , image:'Products/education.png'},
            {id:18, genre:'أدوية', name:'Spiraleuses et Plastifieuses' , tag:'Spiraleuses et Plastifieuses', icon:'' , image:'Products/education.png'},
            {id:19, genre:'أدوية', name:'Etiqueteuses & Rubans' , tag:'Etiqueteuses & Rubans', icon:'' , image:'Products/education.png'},
            {id:20, genre:'أدوية', name:'Affichage & Communication' , tag:'Affichage & Communication', icon:'' , image:'Products/education.png'},
            {id:21, genre:'أدوية', name:'Aménagement de Bureau' , tag:'Aménagement de Bureau', icon:'' , image:'Products/education.png'},
            {id:22, genre:'أدوية', name:'Bagagerie Professionnelle' , tag:'Bagagerie Professionnelle', icon:'' , image:'Products/education.png'},
        ]
    },
    vetements : {
        tableName: '000_abyedh_medicamment' ,
        searchGenre : 'Forme',
        searchSousGenre : 'Forme',
        subCategories : [
            {id:1, genre:'أدوية', name:'T-shirt Et pulls' , tag:'T-shirt Et pulls', icon:'' , image:'Products/vetemment.jpg'},
            {id:2, genre:'أدوية', name:'Manteaux Et Vestes' , tag:'Manteaux Et Vestes', icon:'' , image:'Products/vetemment.jpg'},
            {id:3, genre:'أدوية', name:'Robes' , tag:'Robes', icon:'' , image:'Products/vetemment.jpg'},
            {id:4, genre:'أدوية', name:'Jupes' , tag:'Jupes', icon:'' , image:'Products/vetemment.jpg'},
            {id:5, genre:'أدوية', name:'Pantalons' , tag:'Pantalons', icon:'' , image:'Products/vetemment.jpg'},
            {id:6, genre:'أدوية', name:'Sacs' , tag:'Sacs', icon:'' , image:'Products/vetemment.jpg'},
            {id:7, genre:'أدوية', name:'Ensembles Et tailleurs' , tag:'Ensembles Et tailleurs', icon:'' , image:'Products/vetemment.jpg'},
            {id:8, genre:'أدوية', name:'Chaussures' , tag:'Chaussures', icon:'' , image:'Products/vetemment.jpg'},
            {id:9, genre:'أدوية', name:'Combinaisons' , tag:'Combinaisons', icon:'' , image:'Products/vetemment.jpg'},
            {id:10, genre:'أدوية', name:'Maillots de bain' , tag:'Maillots de bain', icon:'' , image:'Products/vetemment.jpg'},
            {id:11, genre:'أدوية', name:'Accessoires' , tag:'Accessoires', icon:'' , image:'Products/vetemment.jpg'},
            {id:12, genre:'أدوية', name:'Chemises' , tag:'Chemises', icon:'' , image:'Products/vetemment.jpg'},
            {id:13, genre:'أدوية', name:'Lingerie' , tag:'Lingerie', icon:'' , image:'Products/vetemment.jpg'},
            {id:14, genre:'أدوية', name:'Shorts' , tag:'Shorts', icon:'' , image:'Products/vetemment.jpg'},
            {id:15, genre:'أدوية', name:'Gilets' , tag:'Gilets', icon:'' , image:'Products/vetemment.jpg'},
            {id:16, genre:'أدوية', name:'Sweats & pulls' , tag:'Sweats & pulls', icon:'' , image:'Products/vetemment.jpg'},
            {id:17, genre:'أدوية', name:'Vêtements de sport' , tag:'Vêtements de sport', icon:'' , image:'Products/vetemment.jpg'},
            {id:18, genre:'أدوية', name:'Tenues de nuit' , tag:'Tenues de nuit', icon:'' , image:'Products/vetemment.jpg'},
            {id:19, genre:'أدوية', name:'Sacs' , tag:'Sacs', icon:'' , image:'Products/vetemment.jpg'},
            {id:20, genre:'أدوية', name:'Sacs' , tag:'Sacs', icon:'' , image:'Products/vetemment.jpg'},
        ]
    },
    alimentaire : {
        tableName: '000_abyedh_medicamment' ,
        searchGenre : 'Forme',
        searchSousGenre : 'Forme',
        subCategories : [
            {id:1, genre:'أدوية', name:'CHAMIA' , tag:'CHAMIA', icon:'' , image:'Products/medicamment.jpg'},
            {id:2, genre:'أدوية', name:'THONS' , tag:'THONS', icon:'' , image:'Products/medicamment.jpg'},
            {id:3, genre:'أدوية', name:'PREPARATIONS ET CREME' , tag:'PREPARATIONS ET CREME', icon:'' , image:'Products/medicamment.jpg'},
            {id:4, genre:'أدوية', name:'CHOCOLATS & TARTINES' , tag:'CHOCOLATS & TARTINES', icon:'' , image:'Products/medicamment.jpg'},
            {id:5, genre:'أدوية', name:'CAFE ET THE' , tag:'CAFE ET THE', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'CONFITURES' , tag:'CONFITURES', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'TOMATES' , tag:'TOMATES', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'HARISSA ET HROUSS' , tag:'HARISSA ET HROUSS', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'PRODUIT CONSERVEE' , tag:'PRODUIT CONSERVEE', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'HUILE ET BEURRE ' , tag:'HUILE ET BEURRE ', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'CHIPS & INDOUMI' , tag:'CHIPS & INDOUMI', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'BOISSONS' , tag:'BOISSONS', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'CAKES & CAKE CHOCOLAT' , tag:'CAKES & CAKE CHOCOLAT', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'BISCUIT & BUISCUIT CHOCOLAT' , tag:'BISCUIT & BUISCUIT CHOCOLAT', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'FROMAGE & PRODUIT LAITIER' , tag:'FROMAGE & PRODUIT LAITIER', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'VINAIGRES & ZHAR & ETTERCHYA' , tag:'VINAIGRES & ZHAR & ETTERCHYA', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'PATTES & SANS GLUTIN' , tag:'PATTES & SANS GLUTIN', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'EPICES & NUTS' , tag:'EPICES & NUTS', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'COUSCOUS & RIZ' , tag:'COUSCOUS & RIZ', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'SEMOULES & FARINES' , tag:'SEMOULES & FARINES', icon:'' , image:'Products/medicamment.jpg'},
        ]
    },
    cosmetique : {
        tableName: '000_abyedh_medicamment' ,
        searchGenre : 'Forme',
        searchSousGenre : 'Forme',
        subCategories : [
            {id:1, genre:'أدوية', name:'CHAMPOING & TRAITEMMENT & GEL DOUCHE' , tag:'CHAMPOING & TRAITEMMENT & GEL DOUCHE', icon:'' , image:'Products/medicamment.jpg'},
            {id:2, genre:'أدوية', name:'COUCHES & COTTONS' , tag:'COUCHES & COTTONS', icon:'' , image:'Products/medicamment.jpg'},
            {id:3, genre:'أدوية', name:'LINGETTES & PAPIER ' , tag:'LINGETTES & PAPIER ', icon:'' , image:'Products/medicamment.jpg'},
            {id:4, genre:'أدوية', name:'OMO & SAVONS' , tag:'OMO & SAVONS', icon:'' , image:'Products/medicamment.jpg'},
            {id:5, genre:'أدوية', name:'DETERGENTS & DEBOUCHEUR & DETARTRANT' , tag:'DETERGENTS & DEBOUCHEUR & DETARTRANT', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'JAVEL N & P' , tag:'JAVEL N & P', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'VAISELLES' , tag:'VAISELLES', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'ASSOUPLISSANT & GEL MACHINE' , tag:'ASSOUPLISSANT & GEL MACHINE', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'ESTHETIQUE & BAD & GEL' , tag:'ESTHETIQUE & BAD & GEL', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'AIR FRESH & FLITOX' , tag:'AIR FRESH & FLITOX', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'BROSSES & RACLETTES & NAPPES' , tag:'BROSSES & RACLETTES & NAPPES', icon:'' , image:'Products/medicamment.jpg'},
        ]
    },
    technologie : {
        tableName: '000_abyedh_medicamment' ,
        searchGenre : 'Forme',
        searchSousGenre : 'Forme',
        subCategories : [
            {id:1, genre:'أدوية', name:'Solution injectable' , tag:'Solution injectable', icon:'' , image:'Products/medicamment.jpg'},
            {id:2, genre:'أدوية', name:'Solution injectable pour perfusion' , tag:'Solution injectable pour perfusion', icon:'' , image:'Products/medicamment.jpg'},
            {id:3, genre:'أدوية', name:'Poudre pour suspension orale' , tag:'Poudre pour suspension orale', icon:'' , image:'Products/medicamment.jpg'},
            {id:4, genre:'أدوية', name:'Solution à diluer pour perfusion' , tag:'Solution à diluer pour perfusion', icon:'' , image:'Products/medicamment.jpg'},
            {id:5, genre:'أدوية', name:'Comprimé' , tag:'Comprimé', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'Comprimé pelliculé sécable' , tag:'Comprimé pelliculé sécable', icon:'' , image:'Products/medicamment.jpg'},
        ]
    },
    construction : {
        tableName: '000_abyedh_medicamment' ,
        searchGenre : 'Forme',
        searchSousGenre : 'Forme',
        subCategories : [
            {id:1, genre:'أدوية', name:'Solution injectable' , tag:'Solution injectable', icon:'' , image:'Products/medicamment.jpg'},
            {id:2, genre:'أدوية', name:'Solution injectable pour perfusion' , tag:'Solution injectable pour perfusion', icon:'' , image:'Products/medicamment.jpg'},
            {id:3, genre:'أدوية', name:'Poudre pour suspension orale' , tag:'Poudre pour suspension orale', icon:'' , image:'Products/medicamment.jpg'},
            {id:4, genre:'أدوية', name:'Solution à diluer pour perfusion' , tag:'Solution à diluer pour perfusion', icon:'' , image:'Products/medicamment.jpg'},
            {id:5, genre:'أدوية', name:'Comprimé' , tag:'Comprimé', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'Comprimé pelliculé sécable' , tag:'Comprimé pelliculé sécable', icon:'' , image:'Products/medicamment.jpg'},
        ]
    },
    outils : {
        tableName: '000_abyedh_medicamment' ,
        searchGenre : 'Forme',
        searchSousGenre : 'Forme',
        subCategories : [
            {id:1, genre:'أدوية', name:'Solution injectable' , tag:'Solution injectable', icon:'' , image:'Products/medicamment.jpg'},
            {id:2, genre:'أدوية', name:'Solution injectable pour perfusion' , tag:'Solution injectable pour perfusion', icon:'' , image:'Products/medicamment.jpg'},
            {id:3, genre:'أدوية', name:'Poudre pour suspension orale' , tag:'Poudre pour suspension orale', icon:'' , image:'Products/medicamment.jpg'},
            {id:4, genre:'أدوية', name:'Solution à diluer pour perfusion' , tag:'Solution à diluer pour perfusion', icon:'' , image:'Products/medicamment.jpg'},
            {id:5, genre:'أدوية', name:'Comprimé' , tag:'Comprimé', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'Comprimé pelliculé sécable' , tag:'Comprimé pelliculé sécable', icon:'' , image:'Products/medicamment.jpg'},
        ]
    },
    mecanique : {
        tableName: '000_abyedh_medicamment' ,
        searchGenre : 'Forme',
        searchSousGenre : 'Forme',
        subCategories : [
            {id:1, genre:'أدوية', name:'Solution injectable' , tag:'Solution injectable', icon:'' , image:'Products/medicamment.jpg'},
            {id:2, genre:'أدوية', name:'Solution injectable pour perfusion' , tag:'Solution injectable pour perfusion', icon:'' , image:'Products/medicamment.jpg'},
            {id:3, genre:'أدوية', name:'Poudre pour suspension orale' , tag:'Poudre pour suspension orale', icon:'' , image:'Products/medicamment.jpg'},
            {id:4, genre:'أدوية', name:'Solution à diluer pour perfusion' , tag:'Solution à diluer pour perfusion', icon:'' , image:'Products/medicamment.jpg'},
            {id:5, genre:'أدوية', name:'Comprimé' , tag:'Comprimé', icon:'' , image:'Products/medicamment.jpg'},
            {id:6, genre:'أدوية', name:'Comprimé pelliculé sécable' , tag:'Comprimé pelliculé sécable', icon:'' , image:'Products/medicamment.jpg'},
        ]
    },

}
export default SubCat